#! /bin/sh

# run a specific cpp file and time it

filename=$(basename "$1")
executable="${filename%.*}".out

# prevent possible overwrite
# [ -f "$executable" ] &&
#     printf "\033[1;31m*** Naming Conflict ***\033[1;00m\n" && exit 1

# make sure mathutil is up to date
LIBRARY="mathutil.o"
LIB_HDR="mathutil.h"


# check whether source file need LIBRARY
if egrep "^#include\s*\"$LIB_HDR\"" "$filename" > /dev/null
then
    make -s
    # if library does not make successfully
    if [ $? -ne 0 ]; then
        printf "\033[1;31m*** FAIL TO COMPILE LIBRARY ***\033[1;00m\n"
        exit 1
    fi
    g++ -o "$executable" "$filename" $LIBRARY -std=c++11 -O2
else
    g++ -o "$executable" "$filename" -std=c++11 -O2
fi

if [ $? -ne 0 ]; then
    printf "\033[1;31m*** FAIL TO COMPILE %s ***\033[1;00m\n" "$filename"
    exit 1
fi

echo "running $executable"
time ./"$executable"
rm "$executable"
