# Prime power triples
"""
The smallest number expressible as the sum of a prime square, 
prime cube, and prime fourth power is 28. In fact, there are 
exactly four numbers below fifty that can be expressed in such a way:

28 = 22 + 23 + 24
33 = 32 + 23 + 24
49 = 52 + 23 + 24
47 = 22 + 33 + 24

How many numbers below fifty million can be expressed as 
the sum of a prime square, prime cube, and prime fourth power?
"""

from mathutil import prime_under


def num_of_prime_smaller(n, primes):
    for index, i in enumerate(primes):
        if n < i:
            return index
    return len(primes)


def main():
    ceiling = 5 * 10 ** 7
    primes = prime_under(int((ceiling - 2**3 - 2**4) ** 0.5) + 1)
    nums = set()
    print("Primes generated by:", time() - starting_time, "seconds")

    for i in primes:
        for j in primes:
            for k in primes:
                num = i**4 + j**3 + k**2
                if num > ceiling:
                    break
                nums.add(num)
    print(len(nums))


if __name__ == '__main__':
    from time import time
    starting_time = time()
    main()
    print("Time elapsed:", time() - starting_time, "seconds")
